# Generated by Django 4.2.7 on 2024-01-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiobook",
            name="audio_time",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
